### ISSUE TITLE
Love this plugin and some feedback

### ISSUE THREAD

**Issue by olimorris** [emmanueltouzery/decisive.nvim#2]
Firstly, thank you. For those of us who work with CSVs in Neovim, this is a joy of a plugin!

Secondly, a few suggestions after coming to this plugin just now:

- A quick start for those of us who use Lazy.nvim so we can copy and paste it into our config would be great
- A toggle command to align / clear alignments would be handy
- Pasting your video into a GitHub issue so you get a link, and then pasting that link in the README saves me clicking through to https://asciinema.org. The video is great!

**Comment by emmanueltouzery** [comment]
regarding points one and three, a PR would be welcome. I'm not sure how to embed the video better, and while I agree that lazy.nvim is definitely the most prominent package manager, i don't use it myself, so i can't be sure what the exact syntax would be.

regarding point 2, i would be ok to add a toggle, but are you sure it would really be handy? because if you're going to edit the CSV then, despite the recent autocommand, you'll probably have to trigger re-aligning every once in a while. so from that point of view it's handy to allow to align multiple times.
but possibly if it's only to view the csv, or if for your uses, the autocommand really always realigns, then the toggle function could really be handy, in that case i could add it. let me know if that's your case!

**Comment by emmanueltouzery** [comment]
The lazyvim quick guide was added. About the toggle let me know if you have specific use cases or if you really need it after using it for a while. Regarding the video, a PR is welcome!
